name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Create build directory
      run: |
        if [ -d "${{ runner.workspace }}/build" ]; then
          rm -rf "${{ runner.workspace }}/build"
        fi
        mkdir -p "${{ runner.workspace }}/build"
        ls -la "${{ runner.workspace }}"
        
    - name: Run CMake configure
      run: |
        cd "${{ github.workspace }}"  # Use github.workspace instead of runner.workspace
        cmake .
        
    - name: Build project
      run: |
        cd "${{ github.workspace }}"
        cmake --build . --target all -- -j $(nproc)
